### ISSUE TITLE
Custom alphabet?

### ISSUE THREAD

**Issue by dangodev** [TypeCtrl/ts-base32#15]
It’s a shame this package doesn’t have more stars! It’s well-written, and ships with types I need for TypeScript! 🎉 

I started using this because `base32` doesn’t ship with types, but I found it uses the alphabet I need (it’s similar to Crockford, but with minor differences, like swapping `S` for `u`, etc.:

```
0123456789abcdefghjkmnpqrtuvwxyz
```

For full context: we’re using this base32 alphabet in different languages front-end and backend, so swapping it isn’t easy.

Would there be a way to pass a custom alphabet to this library? Thanks!

**Comment by dangodev** [comment]
Just noticed the library lives in `base32-encode`. I’ll open a ticket there, but it’d still need to be an option here too, I think.

**Comment by scttcper** [comment]
feel free to make a pr if you think it fits
